stages:
  - test
  - build
  - deploy

services:
  - docker:dind
cache:
  key: ${CI_COMMIT_REF_SLUG}

# Javascript tasks
lint:
  stage: test
  image: node:14-alpine
  variables:
    STAGE: lint
  before_script:
    - apk add python make g++ git bash
  script:
    - ./cicd/runtasks.sh com/node lib
test:
  stage: test
  image: docker:stable
  variables:
    STAGE: test
    MONGODB: mongodb://docker/
    MONGO: mongodb://mongo/
    RABBITMQ: amqp://docker/
    RABBIT: amqp://rabbitmq/
  before_script:
    - docker run -d -p "27017:27017" --name mongo mongo
    - docker run -d -p "5672:5672" --name rabbitmq rabbitmq
    - apk add python2 make g++ git bash nodejs npm
  script:
    - ./cicd/runtasks.sh com/node lib
build:
  image: docker:stable
  variables:
    DOCKER_DRIVER: overlay2
  stage: build
  variables:
    STAGE: build
  before_script:
    - apk add python2 make g++ git bash nodejs npm
    - if [ ! -z $DOCKER_PASSWORD ]; then docker login --username yusufali -p $DOCKER_PASSWORD; fi
  script:
    - ./cicd/runtasks.sh com/node lib

# terraform
deploy:
  stage: deploy
  image: yusufali/terraform
  before_script:
    - export TF_VAR_WEB_HASH=$(git log -1 --pretty=format:"%h" com/node/web)
  script:
    - cd deployment
    - decrypt secrets
    - source secrets/env
    - terraform init
    - terraform plan
    - if [ "$CI_COMMIT_REF_NAME" = "master" ]; then terraform apply -auto-approve || true; fi
