stages:
  - test
  - build
  - deploy

services:
  - docker:dind
cache:
  key: ${CI_COMMIT_REF_SLUG}

# Javascript tasks
lint:
  stage: test
  image: node:14-alpine
  variables:
    STAGE: lint
  before_script:
    - apk add python make g++ git bash
  script:
    - ./cicd/runtasks.sh web services/node lib
test:
  stage: test
  image: docker:stable
  variables:
    STAGE: test
    MONGODB: mongodb://docker/
    MONGO: mongodb://mongo/
    RABBITMQ: amqp://docker/
    RABBIT: amqp://rabbitmq/
  before_script:
    - docker run -d -p "27017:27017" --name mongo mongo
    - docker run -d -p "5672:5672" --name rabbitmq rabbitmq
    - apk add python2 make g++ git bash nodejs npm
  script:
    - ./cicd/runtasks.sh web services/node lib
build:
  image: docker:stable
  variables:
    DOCKER_DRIVER: overlay2
  stage: build
  variables:
    STAGE: build
  before_script:
    - apk add python2 make g++ git bash nodejs npm
    - if [ ! -z $DOCKER_PASSWORD ]; then docker login --username yusufali -p $DOCKER_PASSWORD; fi
  script:
    - ./cicd/runtasks.sh web services/node lib

# terraform
deploy:
  stage: deploy
  image: docker
  before_script:
    - cd deployment
    - apk add bash unzip wget gnupg curl
    - wget https://releases.hashicorp.com/terraform/0.12.25/terraform_0.12.25_linux_amd64.zip
    - unzip *.zip
    - chmod +x terraform
    - mv terraform /bin/.
    - for f in secrets/*.gpg; do echo $SECRET_PASSPHRASE | gpg -d --batch --yes --passphrase-fd 0 "$f" > "secrets/$(basename $f .gpg)"; done
    - source secrets/env
    - tar xzvf secrets/kube.tar.gz -C secrets/
    - terraform init
  script:
    - terraform plan
    - if [ "$CI_COMMIT_REF_NAME" = "master" ]; then terraform apply -auto-approve || true; fi
